### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by Aericio** [comment]
rofl if you delete 1.0.0 API, plugin wont be functional anymore.

**Comment by SalmonGER** [comment]
This pr is pretty useless in my eyes

**Comment by erkam2002** [comment]
:) i know

**Comment by erkam2002** [comment]
but better

**Comment by TheKnightGamer** [comment]
this is no change

**Comment by ImagicalGamer** [comment]
This plugin was never completed and will never be completed on this repo or publicly (by me at least)

**Pull request closed without merging**
